# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
from openerp.osv import fields, osv

class tarifas_propuestas(osv.osv):
    _name = 'tarifas_propuestas'
  
    
    _columns = {
        'name':fields.char('Tarifa',size=100, required=True,help='Nombre Tarifas Propuestas'),
        'codigo':fields.char('Codigo',size=20, required=True,help='Codigo de las Tarifas Propuestas'),

    }  

class alcance(osv.osv):
    _name = 'alcance'
  
    
    _columns = {
        'name':fields.char('Alcance',size=100, required=True,help=' Nombre del Tipo de Alcance '),
        'tarifas_propuestas_id':fields.many2one('tarifas_propuestas','Tarifa',help=' Relacion de Alcance con tarifas propuestas '),
        'codigo':fields.char('Codigo',size=20, required=True,help='Codigo de los Alcances'),
     
    }
    
class infraestructura(osv.osv):
    _name = 'infraestructura'
   
    
    _columns = {
        'name':fields.char('Infraestructura',size=100, required=True,help=' Nombre del Tipo de infraestructura '),
        'alcance_id':fields.many2one('alcance','Alcance',help=' Relacion de Alcance con infraestructura'),
    }
