# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
from openerp.osv import fields, osv

class registro_parque(osv.osv):
    """Registro de los Parques"""
    _name='registro_parque'
    _inherit='registro_parque'
    
    _columns={
        'est_parques_ids':fields.one2many('estacion_parques','registro_parque_id','Estacion Parques'),
    }

class estacion_parques(osv.osv):
    """Registro de las Estaciones Parques"""
    _name = 'estacion_parques'
    _rec_name='estacion_id'
    
    _columns = {
        'registro_parque_id':fields.many2one('registro_parque','Parques'),
        'estacion_id':fields.many2one('estacion','Estacion Parques',required=True,help='Nombre Estacion Parques'),
        
     
    } 
    
class estacion(osv.osv):
    """Registro de la Estacion"""
    _name = 'estacion'
    
    _columns = {
        'name':fields.char('Estacion Parques',size=100, required=True,help='Nombre de la Estacion'),
    }


